BOT_NAME = 'discordBot'
LOG_ENCODING = 'utf-8'
LOG_FILE_EXTENSION = '.log'
LOG_FILE_PREFIX = 'discordBot_'
LOG_FORMAT_STRING = '%(asctime)s:%(levelname)s:%(name)s: %(message)s by caller %(funcName)s'
LOG_HANDLER_MODE = 'w'
TIME_FORMAT_STRING = '%B-%d@%I:%M:%S'