BOT_NAME = 'discordBot'
LOG_ENCODING = 'utf-8'
LOG_FILE_EXTENSION = '.log'
LOG_FILE_PREFIX = 'discordBot_'
LOG_FORMAT = '%(asctime)s:%(funcName)s - %(levelname)s:%(name)s: %(message)s'
LOG_HANDLER_MODE = 'w'
